spring.application.name: pic-portal-jvm
spring.datasource.url: ${PSQL_URL}
spring.datasource.username: ${PSQL_USER}
spring.datasource.password: ${PSQL_PASSWORD}
spring.liquibase.change-log: db/changelog-master.xml
spring.liquibase.enabled: true
